// leave off @2x/@3x
const images = {
  logo: require('../Images/teamMate.png'),
  g20: require('../Images/G20.png'),
  profile: require('../Images/profile.png'),
  play: require('../Images/play.png'),
  settings: require('../Images/settings.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/teamMate_logo.png'),
  igniteClear: require('../Images/teamMate-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),

  badmintonIcon: require('../Images/EventIcons/badmintonIcon.png'),
  baseballIcon: require('../Images/EventIcons/baseballIcon.png'),
  basketballIcon: require('../Images/EventIcons/basketballIcon.png'),
  bowlingIcon: require('../Images/EventIcons/bowlingIcon.png'),
  cricketIcon: require('../Images/EventIcons/cricketIcon.png'),
  footballIcon: require('../Images/EventIcons/footballIcon.png'),
  frisbeeGolfIcon: require('../Images/EventIcons/frisbeeGolfIcon.png'),
  golfIcon: require('../Images/EventIcons/golfIcon.png'),
  iceHockeyIcon: require('../Images/EventIcons/iceHockeyIcon.png'),
  lacrosseIcon: require('../Images/EventIcons/lacrosseIcon.png'),
  poolIcon: require('../Images/EventIcons/poolIcon.png'),
  soccerIcon: require('../Images/EventIcons/soccerIcon.png'),
  softballIcon: require('../Images/EventIcons/softballIcon.png'),
  tennisIcon: require('../Images/EventIcons/tennisIcon.png'),
  ultimateFrisbeeIcon: require('../Images/EventIcons/ultimateFrisbeeIcon.png'),
  volleyBallIcon: require('../Images/EventIcons/volleyBallIcon.png'),
  otherIcon: require('../Images/EventIcons/otherIcon.png'),
}

export default images
